services:
  pm-tool-postgresdb:
    image: postgres:16
    container_name: pm-tool-postgresdb
    environment:
      POSTGRES_USER: root_username
      POSTGRES_PASSWORD: root_password
      POSTGRES_DB: pm_tool_db
      TZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - pm_tool_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "0.75"
          memory: "1.5g"
        reservations:
          cpus: "0.5"
          memory: "0.5g"

volumes:
  pm_tool_data:
